name: Coverage PRs - only changed components

on:
  pull_request:
    branches:
      - master
    paths:
      - 'app/donkey/**'
      - 'app/monkey/**'


jobs:

  # A special job solely to detect which components have changed
  # Based on the detected changes, we then only run specific coverage jobs below
  # cs-coverage-check is executed once and only once - always after the *-coverage jobs completed
  changes:
    runs-on: ubuntu-24.04
    # Set job outputs to values from filter step
    outputs:
      monkey: ${{ steps.filter.outputs.monkey }}
      donkey: ${{ steps.filter.outputs.donkey }}
    # Required permissions for detecting changes inside PRs via GitHub API
    permissions:
      pull-requests: read
    steps:
      # For pull requests it's not necessary to checkout the code
      #- uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            monkey:
              - 'app/monkey/**'
            donkey:
              - 'app/donkey/**'

  coverage-monkey:
    needs: changes
    if: ${{ needs.changes.outputs.monkey == 'true' }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./app/monkey
    steps:
      - uses: actions/checkout@v4
      - name: Run tests with coverage
        run: mvn clean test
      - uses: actions/upload-artifact@v4
        with:
          path: calculator-1/target/site/jacoco/jacoco.xml
          # since we have multiple components we must use distinct artifact names
          # see also `coverage-files` attribute inside `cs-coverage-check` job below
          name: monkey.cobertura.xml

  coverage-donkey:
    needs: changes
    if: ${{ needs.changes.outputs.donkey == 'true' }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./app/donkey
    steps:
      - uses: actions/checkout@v4
      - name: Run tests with coverage
        run: mvn clean test
      - uses: actions/upload-artifact@v4
        with:
          path: calculator-2/target/site/jacoco/jacoco.xml
          name: donkey.cobertura.xml

  cs-coverage-check:
    runs-on: ubuntu-24.04
    needs: [ coverage-monkey, coverage-donkey ]
    # NOTE: 'always()' is needed here because we want to run this step even if some of its dependencies fail
    if: always()
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch everything so that `cs-coverage check` can find merge-base.
          fetch-depth: 0
        # Download all artifacts/coverage files: https://github.com/actions/download-artifact#download-all-artifacts
        # this also affects `coverage-files` property in the subsequent step
      - name: download coverage
        uses: actions/download-artifact@v5
        with:
          path: coverage/
      - uses: ./.github/actions/check-coverage
        if: always()
        with:
          access-token: ${{ secrets.CODESCENE_CODE_COVERAGE_API_TOKEN }}
          project-url: "https://api.codescene.io/v2/projects/72308"
          # Include coverage files from all the artifacts (jobs)
          # NOTE:: if only one component is analyzed then there's only a single coverage/jacoco.xml file
          # If multiple components, then the files are nested: coverage/calculator1.jacoco.xml/jacoco.xml, coverage/calculator1.jacoco.xml/jacoco.xml, etc.
          coverage-files: "**/coverage/**/cobertura.xml"
